source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod “WeiboSDK”, :git => “https://github.com/sinaweibosdk/weibo_ios_sdk.git”
pod 'AFNetworking', '~> 3.0.0-beta.1'
pod 'SDWebImage'
pod 'MJRefresh'

